config/routes.rb
Todo::Application.routes.draw do
  get "about/index"

  resources :chores

  root :to => 'chores#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  attr_accessible :ch_completed, :ch_date, :ch_name
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(params[:chore])

    respond_to do |format|
      if @chore.save
        format.html { redirect_to @chore, notice: 'Chore was successfully created.' }
        format.json { render json: @chore, status: :created, location: @chore }
      else
        format.html { render action: "new" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])

    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to @chore, notice: 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy

    respond_to do |format|
      format.html { redirect_to chores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/about/index.html.erb
<h3>About Me...</h3>
<address>
  <strong>Natasha Ansari</strong><br>
  123 Main Street<br>
  Asheville, NC 28801<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890<br>
  <a href="mailto:#">natashayansari@students.abtech.edu</a>
</address>
<%= link_to 'Back', chores_path %>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Chore %><br />
    <%= f.text_field :ch_name %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :ch_date %>
  </div>
  <div class="field">
    <%= f.label :Completed? %><br />
    <%= f.check_box :ch_completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h3>Editing chore</h3>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h3>Listing chores</h3>

<table>
  
  <tr>
    <th class="col-md-2">Chore</th>
    <th class="col-md-2">Date</th>
    <th class="col-md-2">Completed?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% @chores.each do |chore| %>
  <tr>
    <td class="col-md-2"><%= chore.ch_name %></td>
    <td class="col-md-2"><%= chore.ch_date %></td>
    <td class="col-md-2"><%= chore.ch_completed %></td>
    <td>
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Choose...
        <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <li><%= link_to 'Show', chore %></li>
          <li><%= link_to 'Edit', edit_chore_path(chore) %></li>
          <li><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'About', controller: 'about', action: 'index' %></li>

        </ul>
      </div>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h3>New chore</h3>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Chore:</b>
  <%= @chore.ch_name %>
</p>

<p>
  <b>Date:</b>
  <%= @chore.ch_date %>
</p>

<p>
  <b>Completed:</b>
  <%= @chore.ch_completed %>
</p>


<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="custom.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<h1>To do...</h1>
<div class="container-fluid">
<%= yield %>
</div>


</body>
</html>